### PR TITLE
Very minor change in README.md

### PR DESCRIPTION
**Pull request by LOLwierd**
Changed a 's' in the first link of README.md to a 'z'.

### CODE REVIEW

**Comment by escamoteur** [comment]
I, thanks but the s is correct it's just British English

**Comment by LOLwierd** [comment]
Yes but the link does not work due to the use of s.

**Comment by escamoteur** [comment]
Upps, sorry. Fixed it now but won't push another version yet. gets included with the next version

**Comment by LOLwierd** [comment]
;)

**Pull request closed without merging**
