### PR TITLE
Add scopeName parameter to popScope

### PR DESCRIPTION
**Pull request by olexale**
Let's imagine an object (it could be a complex stateful widget, a page, or an anchor in AR) that has complex internal dependencies (object-scoped services, repositories, etc.). I found it highly convenient to push a separate named scope during this object creation and lazily initialize its dependencies. The problem is that, when the object dies, I cannot remove the scope without popping scopes that potentially were pushed on top of it, i.e. it is not possible to drop the scope B without dropping scope C as well:
```
[scope A] -> [scope B] -> [scope C]
```

With this PR I propose adding functionality that allows dropping any named scope from the stack.

### CODE REVIEW

**Review by tide-lazo — APPROVED** [review]

**Review by cyrilnoah1 — APPROVED** [review]

**Review by vladattide — APPROVED** [review]

**Review by jaxfire — APPROVED** [review]

**Review by dragoshrock — APPROVED** [review]

**Review by svetlin-tide — APPROVED** [review]

**Review by vivekkartha7 — APPROVED** [review]

**Review by gvozditskiy — APPROVED** [review]

**Comment by escamoteur** [comment]
I know that it's been a long time, but I had to make a longer break due to health issues. 
Wouldn't that be more a `disposeScope` than a `popScope`?

**Comment by olexale** [comment]
In the beginning, I named the method `dropScope`, I cannot recall the exact reason for relocating the implementation to `popScope` and introducing a parameter. `disposeScope` also seems logical to me. 

I'm happy to refactor the proposed implementation. Which method name would you prefer? Should we go with `disposeScope`?

**Comment by escamoteur** [comment]
Yeah, I think disposeScope makes sense because it is probably called because people want to dispose of all objects in it.
may I also invite you to the discussion here: https://github.com/escamoteur/watch_it/issues/1

**Comment by escamoteur** [comment]
thinking a bit more (toilet break :-) ) `dropScope` might indeed be better because it transports better the meaning that the scope is not only dropped but also disposed.

**Comment by olexale** [comment]
I extracted the functionality into `dropScope` and updated the `readme`. Unfortunately, tests are failing now, but I see they are failing in the `master` branch, so I assume it's a common problem.
I'll investigate why this happens later today if the issue is not resolved before that.

**Comment by olexale** [comment]
It looks like tests are failing because `assert`s were replaced with `throwIfNot` (like in [this commit](https://github.com/fluttercommunity/get_it/commit/144c708992de4a41c429c09cb9a1763726ef39d6)). I see that these changes were added 5 hours ago, so you are probably working on them now. To make tests pass locally I just replaced
```dart
throwsA(const TypeMatcher<AssertionError>()),
```
with
```dart
throwsA(const TypeMatcher<StateError>()),
```

I'm happy to raise additional PR with the fix if needed.

**Comment by escamoteur** [comment]
Thanks a lot for this PR

**Comment by escamoteur** [comment]
Included in just pushed V7.5.0

**Comment by olexale** [comment]
Thank you!

**Comment by escamoteur** [comment]
thanks to your PR I now could finally make pushScope in the get_it_mixin more secure https://github.com/escamoteur/get_it_mixin/blob/master/CHANGELOG.md#420---22032023

**Comment by olexale** [comment]
We use functionality similar to `pushScope` from the `get_it_mixin` a lot. Without it, the whole codebase was full of dependency overrides, and I needed to track and align our `get_it` fork with the original. 
Thanks for merging the PR, this simplified my life a bit 🙂

**Pull request merged**
