### PR TITLE
Add the meta package to pubspec to fix pub analysis issues

### PR DESCRIPTION
**Pull request by miyoyo**
Without the meta package as a dependency, Pub is unable to classify this package as the analysis fails.
This also severely hurts the health score.

### CODE REVIEW

**Comment by escamoteur** [comment]
Interesting, any source about the meta package needed on pub?
First time I hear of it.

**Comment by miyoyo** [comment]
I see that in earlier versions this package used to depend on Flutter, which [depends on many packages](https://api.flutter.dev) (anything on the left of the page is part of flutter), maybe this is why warnings didn't use to appear?

Whatever the case may be, Pub requires it now and it doesn't seem to be able to resolve it
Screenshot_2019-08-19-10-24-49-730_com kiwibrowser browser

**Comment by escamoteur** [comment]
Thanks again for pointing it out. I need to push a new version anyway today because I forgot to clear the string map in reset.

**Comment by escamoteur** [comment]
Just pushed V2.0.1 thanks for contributing

**Pull request merged**
