### PR TITLE
isFinal test

### PR DESCRIPTION
**Pull request by subzero911**
https://github.com/fluttercommunity/get_it/issues/326

I added a test but it fails for some reason.

TestClass is not removed after popScope().

### CODE REVIEW

**Comment by escamoteur** [comment]
I merge and debug

**Comment by escamoteur** [comment]
you have to await popScope

**Comment by escamoteur** [comment]
because dispose functions can be async
if you don't await in the test the expect will get executed before the scope is popped

**Comment by escamoteur** [comment]
if fixed it and pushed it again

**Comment by escamoteur** [comment]
do you also update the readme?

**Comment by subzero911** [comment]
> you have to await popScope

Add a couple of lints to `analysis_options`, to avoid such errors in the future:
```
    - unawaited_futures
    - discarded_futures
```

> do you also update the readme?

no, it's better if you describe the improvements.

**Comment by subzero911** [comment]
https://github.com/fluttercommunity/get_it/pull/330

**Pull request merged**
