### PR TITLE
Return the instance when calling registerSingleton

### PR DESCRIPTION
**Pull request by Rexios80**
Just a convenience feature so you can write code like this:
```dart
final instance = GetIt.I.registerSingleton(Object());
```

### CODE REVIEW

**Comment by escamoteur** [comment]
Hi, sorry for not looking into this earlier, but I had some mental health problems the last half year.

Why do you think this is better than

```
final instance = Object();

GetIt.I.registerSingleton(instance);
```

**Comment by Rexios80** [comment]
It's mostly for convenience, but it also lets you register a singleton like this:

```dart
class Class {
    final instance = GetIt.I.registerSingleton(Object());
}
```

Which isn't possible otherwise

**Comment by escamoteur** [comment]
I see, but why do you store the instance at all outside of get_it?
Am 3. Feb. 2022, 19:01 +0100 schrieb Rexios ***@***.***>:

**Comment by Rexios80** [comment]
For myself I use it for more convenient initialization of the singleton:
```dart
final instance = GetIt.I.registerSingleton(Object());
instance.setup();
instance.doOtherStuff();
```

Not a huge deal to split the first line into two, but again this is just for convenience.

**Comment by escamoteur** [comment]
@esDotDev What do you think?

**Comment by esDotDev** [comment]
I think darts chaining ability makes this a bit redundant.
```
final instance = Object()..setup()..doOtherStuff();
GetIt.I.registerSingleton(instance);
```
On the other hand, it cant really hurt, and is a small quality of life thing, so why not?

**Comment by escamoteur** [comment]
What I don't like is that it would break the format of the other registerFunctions.

**Comment by Rexios80** [comment]
Couldn't we make those do the same thing?

**Comment by escamoteur** [comment]
Unfortunately no, because all the registerFuncions that take a factoryfuncion return without creating an instance

**Comment by esDotDev** [comment]
I think if it's lazy, it's obvious why it wouldn't return anything. Seems ok to me.

**Comment by esDotDev** [comment]
If we did want to have similar functionality lazily, an `onCreated: (instance){ }` method could be nice?

**Comment by Rexios80** [comment]
Just a random thought: you can't await chained async calls

**Comment by escamoteur** [comment]
I know this is a pretty old PR but I had to make a break over the last year

**Pull request merged**
